// apps/playground-react/src/App.tsx
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        {/* @ts-ignore */}
        <ui-button variant="secondary" size="md">Web Component</ui-button>
        <p>
      Edit <code>src/app/app.component.html</code> and save to test HMR
    </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App

// apps/playground-angular/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppComponent {
  title = 'playground-angular';
}

<main class="main">
  <div class="logos">
    <a href="https://vitejs.dev" target="_blank" rel="noopener">
      <img src="https://vitejs.dev/logo.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vitejs.dev" target="_blank" rel="noopener">
      <img src="https://v7.angular.cn/assets/images/logos/angular/angular.svg" class="logo" alt="Vite logo" />
    </a>
  </div>

  <h1>Vite + Angular</h1>

  <div class="card">
    <ui-button variant="secondary" size="md">Web Component</ui-button>
    <p>
      Edit <code>src/app/app.component.html</code> and save to test HMR
    </p>
  </div>

  <p class="read-the-docs">
    Click on the Vite and Angular logos to learn more
  </p>
</main>
